### ISSUE TITLE
Consider implementing NewPipe Extractor or similar

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#5264]
### Describe your suggested feature

As Piped instances get blacklisted and Google makes changes that break Libretube and instances it relies on, - while the app itself also experiences frequent fatal crashes - Newpipe always manages to access the streams unaccessible via LibreTube and stay stable.

To a regular user it's a much better experience, as they do not need to wait for instances or for the app to get patched (which do happen but rarely abd get patched quickly). This also eliminates the headache for more literate users who might recommend one app or the other to their families and friends, and then having to try to troubleshoot it for them often, maybe even forcing users to downgrade to their original YouTube watching methods like the official app. 

Hence why I would like to ask to implement NewPipe Extractor in some form, or another alternative that is more stable. I do understand that as software NPE is not without it's flaws and there are reasons why it's not used in the first place in it's current or modified form, like the IP tracking concerns but at this point that would be no different than "Disable piped proxy" togle, which still does not make the streams work.

I really like this app, currently this is one of the best modern alternatives to vanilla YouTube and I would love for it to become more stable so I could recommend it more freely.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IndusAryan** [comment]
not only newpipe but the YT's own Innertube can be added or cloudstream's direct scrapers  but this app is privacy focused first no matter what shit happens to playback and layout and user experience, lags crashes but IP should not be leaked

**Comment by ticklemyIP** [comment]
I feel like a compromise can be made. Just as the interface warns that you should be using a VPN when disabling the proxy it could warn when the user enables alternative access methods.

It could even provide this option on a first start sceen if that is something that will get implemented. Maybe even a simple status indicator on the interface somewhere that clarifies which service is being used.

**Comment by Ciancy28** [comment]
I feel exactly the same.   
While I like LibreTube's ui and features more than newpipe, it's been 3 days since the last time I was able to actually watch a video on it, pretty much useless in its current state.   
NewPipe on the other hand, mostly just works.   
I understand that using an instance makes your browsing fully private while newpipe extractor doesn't, but many users (including me) don't really care about that and use these alternative clients for other reasons, as the above comment suggested, just put up a warning before switching to newpipe extractor for those that care about their IP not being given to google.

**Comment by JohnBetaro** [comment]
I really hope the developer will consider adding this feature because I wanted to talk about it a long time ago, hopefully the issue will not be closed as not planned.

It is very terrible having always Newpipe installed alongside LibreTube because you know that the app will not work properly sometimes and requires you to jump from one instance to another, and this time the problem cannot even be solved in a short time and we are left days not being able to watch.

I really like the app and the commitment of the developer but this issue should be solved at least by giving the users the choice to choose what they want to use since the main option is not stable.

**Comment by IndusAryan** [comment]
there is another loophole i think it won't require any change on libretube side but on piped backend-
that the piped instances themselves have settings to scrape from yt using amy api like newpipe extractor or innertube or luanrt's youtube js etc

**Comment by Pamilg8** [comment]
Comparison to the YouTube Data v3 API
The official API requires a Google account to use, while the InnerTube API can do it without the need of one.

The official API has a request quota and a request rate limit, while the InnerTube API does not have any limitations.

The official API is designed to be used by 3rd parties, thus, the data is formatted well. Since the InnerTube API is made to be used in the official YouTube apps, it is formatted to render elements on a screen. This makes it slightly harder to parse the output to a human readable format, which this library tries to do.

**Comment by Bnyro** [comment]
Already rejected in https://github.com/libre-tube/LibreTube/issues/1121#issuecomment-1223619503, and the reason is still the same. I don't have time to maintain that and Piped works reliably when you self-host it or use a small instance.
Without using Piped, many things wouldn't work anymore as they did and changing all that is nothing I have time or motivation for.
